from draftfast.constants.roster_size import ROSTER_SIZE_BY_SITE_BY_SPORT
from draftfast.constants.positions import (
    POSITIONS_BY_SITE_BY_LEAGUE,
    NBA_GENERAL_POSITIONS,
    MLB_GENERAL_POSITIONS,
    WNBA_GENERAL_POSITIONS,
)
from draftfast.constants.salary_cap import SALARY_CAP_BY_SITE_BY_LEAGUE

assert ROSTER_SIZE_BY_SITE_BY_SPORT
assert POSITIONS_BY_SITE_BY_LEAGUE
assert NBA_GENERAL_POSITIONS
assert MLB_GENERAL_POSITIONS
assert WNBA_GENERAL_POSITIONS
assert SALARY_CAP_BY_SITE_BY_LEAGUE
