from draftfast.constants.roster_size import ROSTER_SIZE_BY_SITE_BY_SPORT
from draftfast.constants.positions import POSITIONS_BY_SITE_BY_LEAGUE
from draftfast.constants.salary_cap import SALARY_CAP_BY_SITE_BY_LEAGUE

assert ROSTER_SIZE_BY_SITE_BY_SPORT
assert POSITIONS_BY_SITE_BY_LEAGUE
assert SALARY_CAP_BY_SITE_BY_LEAGUE
