name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt; pip install -r test-requirements.txt
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Run Tests
        run: nose2
